Sinatraプラクティスのメモアプリ作成
hikaroox/sinatra-practice pull request #2
Opened 2022-04-05 08:43 UTC by hikaroox

2022-04-10 16:08 UTC, u1tnk requested changes

2022-04-10 16:08 UTC, u1tnk commented on myapp.rb
> +  @hash = File.open('./data.json') { |f| JSON.parse(f.read) }
`@hash` というのは変数名として良くないです。
型情報しか無いのでhashに何が入っているかまったく分からないので、中身のデータが推測できるような名前に変更しましょう。

2022-04-10 16:08 UTC, u1tnk commented on myapp.rb
> +  json = File.open('./data.json', 'r') { |f| JSON.parse(f.read) }
get の方では `r`オプション無しで、`hash`に入れていてこちらでは `r`オプション有りで `json`に入れていると一貫性が無いので統一しましょう。
とはいえ、この処理は以降でも頻出なので書き方を統一するよりもメソッド化して共有化した方が良いでしょう。

2022-04-10 16:08 UTC, u1tnk commented on myapp.rb
> +  json[params['memo_id']]['title'] = ERB::Util.html_escape(params['title'])
railsでもsinatraでもデフォルトで viewで出力するときは何もしなくても html_escapeされます(むしろそのまま出力するときに操作が必要)ので保存時点でescapeする必要はありませんのでそのまま保存しましょう。

2022-04-10 16:08 UTC, u1tnk commented on myapp.rb
> +  File.open('./data.json', 'w') { |f| JSON.dump(json, f) }
同様に書く方も共通化すると良いですね。

2022-04-10 16:08 UTC, u1tnk commented on myapp.rb
> +    'title' => ERB::Util.html_escape(params['title']),
後述していますが、html_escapeする必要は無いですね。

2022-04-11 06:03 UTC, hikaroox commented on myapp.rb
> +  json[params['memo_id']]['title'] = ERB::Util.html_escape(params['title'])
レビューありがとうございます！
`html_escape` なしでform部分に`<script>alert('hi');</script>` を入れてみたところエスケープされずにスクリプトが実行されてしまうようです（data.jsonの中にもエスケープされずにデータが登録されていました）。
なのでコードの中でのエスケープ処理は必要だと思うのですが、何か設定が必要でしょうか？

2022-04-11 12:54 UTC, u1tnk commented on myapp.rb
> +  json[params['memo_id']]['title'] = ERB::Util.html_escape(params['title'])
申し訳ありませんsinatraだと勝手にしてくれないようです。
sinatraのドキュメント見たつもりだったんですが…失礼致しました 🙏 
せめて根拠のsinatraのページを貼るべきでしたが何かワードが違ったよう見つからず…指摘の方法としても良くなかったです 🙏 

となるとやはり必要になりますが、 html_escapeはviewのerb内で出力するときにやりましょう。データベース(今回はjson)内のデータは入力したままであるべきなので。railsでもviewでescapeしています。
_

2022-04-12 03:50 UTC, u1tnk approved these changes
細かい指摘一点ありますが、ほぼ問題無いのでOKです！

2022-04-12 03:50 UTC, u1tnk commented on views/index.erb
> +    <% @memos_hash.each_with_index do |n,idx| %>
細かいですけど、慣習的に indexは `i`で大丈夫です。

2022-04-12 07:04 UTC, merged